### ISSUE TITLE
Manual Annotation Tool Broken

### ISSUE THREAD

**Issue by zjniu** [arjunrajlaboratory/NimbusImage#204]
The manual annotation tool is broken (both point and blob) upon merging the add-annotation-worker branch. Currently, each annotation has a black border around them when added, which indicates that it has not yet registered in the system. They do not get added to the annotation list
<img width="370" alt="Screen Shot 2022-03-25 at 12 59 08 AM" src="https://user-images.githubusercontent.com/87096829/160435217-8bbad2cb-f961-4d3a-a310-97c951c94ca3.png">
.

**Comment by boucaud** [comment]
This should be fixed now.
